cmd/trdl/bin_path.go, cmd/trdl/common.go, cmd/trdl/dir_path.go, cmd/trdl/exec.go, cmd/trdl/list.go, cmd/trdl/main.go, cmd/trdl/set_default_channel.go, cmd/trdl/update.go, pkg/client/client.go, pkg/client/configuration.go, pkg/client/interface.go, pkg/trdl/const.go, pkg/util/exec_unix.go, pkg/util/exec_windows.go
- add `trdl set-default-channel REPO CHANNEL` command
- rework CLI and client pkg
=> feat: default channel support 

.github/workflows/trdl_releaser.yml
Release trdl client using trdl-vault-server.
=> ci: add trdl releaser workflow

cmd/trdl/use.go, e2e/tests/flow/use_test.go, pkg/client/client.go, pkg/client/interface.go, pkg/repo/use.go
Create the script and print the path for sourcing by default
=> refactor: drop --as-file option for use command

.github/workflows/trdl_releaser.yml
- bump version
- generate CHANGELOG.md
=> ci: update trdl releaser workflow

client/pkg/repo/use.go
```
Error: channel "alpha" not found locally (group: "1"), update channel with "trdl update test 1 alpha" command
```
=> fix(client): the use command does not work properly in powershell

server/path_publish.go, server/path_release.go, server/pkg/publisher/interface.go, server/pkg/publisher/publisher.go, server/pkg/publisher/repository.go, server/pkg/util/logical_error.go
1. Do not allow non existing releases specified in the trdl_channels.yaml.
2. Do not allow channel duplication withing group and group duplication in the trdl_channels.yaml.
3. Do not allow release versions to be specified with "v" prefix letter.
=> fix(server): publish procedure validation

client/scripts/ci/build_release_v2.sh
Use bin dir in trdl release structure.
=> infra: fix release build script for trdl

client/cmd/trdl/main.go, client/cmd/trdl/remove.go, client/pkg/client/client.go, client/pkg/client/configuration.go, client/pkg/client/interface.go
=> feat(client): add remove command

docs/_data/sidebars/_reference.yml, docs/_data/sidebars/reference.yml, docs/pages_en/reference/trdl_channels_yaml.md, docs/pages_en/reference/trdl_yaml.md
- hide "TUF repository layout" en article
- sync with ru
=> docs: small improvements

docs/pages_en/reference/tuf_repository_layout.md, docs/pages_ru/reference/tuf_repository_layout.md
- translate tuf_repository_layout.md
- fix the English link (semver.org/lang -> semver.org)
- fix the Russian link (semver.org/lang -> semver.org/lang/**ru**)
=> Translate tuf_repository_layout.md

.github/workflows/docs_cli_and_api_partials_checker.yml, .github/workflows/website_broken_links_checker.yml, docs/Gemfile, docs/Gemfile.lock, docs/_data/sidebars/_cli.yml, docs/_data/sidebars/reference.yml, docs/_includes/reference/cli/trdl_remove.md, docs/_includes/reference/cli/trdl_remove.short.md, docs/_includes/reference/cli/trdl_version.md, docs/_includes/reference/cli/trdl_version.short.md, docs/_includes/reference/vault_plugin/configure.md, docs/_includes/topnav.html, docs/pages_en/reference/cli/overview.md, docs/pages_en/reference/cli/trdl_remove.md
- CLI/API partials checker 
- Broken links checker
=> ci: check broken links and relevance of CLI/API partials

docs/Makefile
=> docs(makefile): mistakes were made... again

client/trdl_channels.yaml
=> chore(client): update release channels

docs/.helm/templates/20-ingress-tuf-router.yaml, docs/.helm/templates/20-ingress.yaml
Update Ingress API version on the site
=> site: update Ingress API version

docs/pages_ru/QUICKSTART.md
=> docs(quickstart): managing trusted GPG keys

e2e/tests/client/basic_test.go, e2e/tests/client/suite_test.go
=> test(e2e): self-update

.github/workflows/trdl_publisher.yml
=> ci(publisher): run workflow on changes in trdl_channels.yaml files

docs/css/components/index/_benefits.scss, docs/pages_en/index.html, docs/pages_ru/index.html
=> site: homepage restructuring

server/pkg/pgp/util.go
Signed-off-by: Timofey Kirillov <timofey.kirillov@flant.com>
=> fix: panic when checking signatures

.golangci.yaml, client/Makefile, server/Makefile
=> chore: fix/update linters/formatters

.github/workflows/docs_cli_and_api_partials_checker.yml, .github/workflows/lint.yaml, .github/workflows/tests.yml, .github/workflows/website_broken_links_checker.yml, .github/workflows/website_converge.yml, .github/workflows/website_review.yml, .github/workflows/website_review_dismiss.yml, .github/workflows/website_test.yml
=> chore: refactor CI, make it up to date

e2e/Makefile
=> chore(e2e): add Makefile with lint/fmt targets

client/pkg/repo/use.go, server/pkg/git/signatures.go
```
export TRDL_USE_<REPO>_GROUP_CHANNEL=<GROUP> <CHANNEL>
```
=> feat(client): export environment variable with a used group and channel in the source script

Taskfile.dist.yaml
=> chore(Taskfile): add sign task

client/trdl_channels.yaml
=> chore(channels): 0.6.3 to 0 alpha

docs/.helm/templates/10-app.yaml, docs/.helm/templates/14-tuf-router.yaml
Actualization apiVersion of PodDisruptionBudget to policy/v1
=> [flant] Update PodDisruptionBudget apiVersion

client/trdl.yaml, server/trdl.yaml
=> chore(server, release): fix failed release build
